# HatsOff installer for Windows
# Usage:
#   powershell -ExecutionPolicy Bypass -File .\install.ps1
#   .\install.ps1 -NoRun
#   .\install.ps1 -Update
# After install:  hatsoff   (desktop)    hatsoff-agent   (CLI)

param(
    [switch]$NoRun,
    [switch]$Update,
    [switch]$Help
)

$ErrorActionPreference = "Stop"

if ($Help) {
    Write-Host "Usage: .\install.ps1 [-NoRun] [-Update]"
    Write-Host "  -NoRun    install deps/launcher, do not start HatsOff"
    Write-Host "  -Update   git pull + reinstall Python deps (implies -NoRun)"
    Write-Host "After install, run:  hatsoff   or   hatsoff-agent"
    exit 0
}

if ($Update) {
    $NoRun = $true
}

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $Root

$Prefix = Join-Path $env:LOCALAPPDATA "HatsOff"
$BinDir = Join-Path $Prefix "bin"
$VenvDir = Join-Path $Root ".venv"

Write-Host "========================================"
Write-Host "  HatsOff - Windows installer"
Write-Host "========================================"
Write-Host "Project: $Root"
Write-Host ""

if ($Update) {
    if (Test-Path (Join-Path $Root ".git")) {
        Write-Host "[*] Updating from git..."
        try {
            git pull --ff-only
        } catch {
            git pull
        }
    } else {
        Write-Host "[!] Not a git checkout - skipping pull"
    }
}

function Find-Python {
    $pyLauncher = Get-Command py -ErrorAction SilentlyContinue
    if ($pyLauncher) {
        try {
            & py -3 -c "import sys; print(sys.version)" 2>$null | Out-Null
            if ($LASTEXITCODE -eq 0) {
                return @{ Exe = "py"; Args = @("-3") }
            }
        } catch {}
    }
    $pythonCmd = Get-Command python -ErrorAction SilentlyContinue
    if ($pythonCmd) {
        try {
            & python -c "import sys; print(sys.version)" 2>$null | Out-Null
            if ($LASTEXITCODE -eq 0) {
                return @{ Exe = "python"; Args = @() }
            }
        } catch {}
    }
    return $null
}

$Py = Find-Python
if (-not $Py) {
    Write-Host "[!] Python 3 not found. Install from https://www.python.org/downloads/"
    Write-Host "    Tip: check 'Add python.exe to PATH' during setup."
    exit 1
}

Write-Host "[*] Python: $($Py.Exe) $($Py.Args -join ' ')"

$VenvPython = Join-Path $VenvDir "Scripts\python.exe"
$NeedVenv = $true
if (Test-Path $VenvPython) {
    & $VenvPython -c "import sys" 2>$null | Out-Null
    if ($LASTEXITCODE -eq 0) {
        $NeedVenv = $false
    } else {
        Write-Host "[*] Existing .venv is broken (missing Python) - recreating"
    }
}
if ($NeedVenv) {
    Write-Host "[*] Creating .venv..."
    if (Test-Path $VenvDir) {
        Remove-Item -Recurse -Force $VenvDir
    }
    $venvArgs = $Py.Args + @("-m", "venv", $VenvDir)
    & $Py.Exe @venvArgs
    if (-not (Test-Path $VenvPython)) {
        Write-Host "[!] Failed to create venv"
        exit 1
    }
} else {
    Write-Host "[*] Reusing existing .venv"
}

Write-Host "[*] Installing Python packages..."
& $VenvPython -m pip install --upgrade pip
$Req = Join-Path $Root "requirements\pip-requirements.txt"
& $VenvPython -m pip install -U -r $Req

$Cfg = Join-Path $Root "agents\utils\api.config.json"
$Exa = Join-Path $Root "agents\utils\api.config.example.json"
if ((-not (Test-Path $Cfg)) -and (Test-Path $Exa)) {
    Copy-Item $Exa $Cfg
    Write-Host "[*] Created agents\utils\api.config.json - set keys in Settings"
}

function Write-HatsOffLauncher {
    param(
        [string]$CommandName,
        [string]$PythonModule,
        [switch]$UseCallerCwd
    )
    $cmdLines = @(
        "@echo off"
        "REM HatsOff launcher (generated by install.ps1)"
        "set `"ROOT=$Root`""
        "set `"VENV=%ROOT%\.venv\Scripts\python.exe`""
        "if not exist `"%VENV%`" ("
        "  echo [!] Missing venv. Run: powershell -ExecutionPolicy Bypass -File `"%ROOT%\install.ps1`" -NoRun"
        "  exit /b 1"
        ")"
        "set `"PYTHONPATH=%ROOT%;%PYTHONPATH%`""
    )
    if ($UseCallerCwd) {
        $cmdLines += @(
            "set `"HATSOFF_WORKSPACE=%CD%`""
            "`"%VENV%`" -m $PythonModule %*"
        )
    } else {
        $cmdLines += @(
            "cd /d `"%ROOT%`""
            "`"%VENV%`" -m $PythonModule %*"
        )
    }
    $unixRoot = $Root -replace '\\', '/'
    $shLines = @(
        "#!/bin/sh"
        "ROOT=`"$unixRoot`""
        "VENV=`"`$ROOT/.venv/Scripts/python.exe`""
        "if [ ! -f `"`$VENV`" ]; then"
        "  echo `"[!] Missing venv. Run: powershell -ExecutionPolicy Bypass -File `"`$ROOT/install.ps1`" -NoRun`""
        "  exit 1"
        "fi"
        "export PYTHONPATH=`"`$ROOT`${PYTHONPATH:+:`$PYTHONPATH}`""
    )
    if ($UseCallerCwd) {
        $shLines += @(
            "export HATSOFF_WORKSPACE=`"`$(pwd)`""
            "exec `"`$VENV`" -m $PythonModule `"$@`""
        )
    } else {
        $shLines += @(
            "cd `"$unixRoot`" || exit 1"
            "exec `"`$VENV`" -m $PythonModule `"$@`""
        )
    }
    $cmdPath = Join-Path $BinDir "$CommandName.cmd"
    $shPath = Join-Path $BinDir $CommandName
    $localCmd = Join-Path $Root "$CommandName.cmd"
    $cmdLines | Set-Content -Path $cmdPath -Encoding ASCII
    $cmdLines | Set-Content -Path $localCmd -Encoding ASCII
    $shLines | Set-Content -Path $shPath -Encoding ASCII
    Write-Host "[*] Installed command: $cmdPath"
    Write-Host "[*] Git Bash launcher: $shPath"
}

New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
Write-HatsOffLauncher -CommandName "hatsoff" -PythonModule "agents.desktop"
Write-HatsOffLauncher -CommandName "hatsoff-agent" -PythonModule "agents.cursor" -UseCallerCwd
$Wrapper = Join-Path $BinDir "hatsoff.cmd"

$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
if (-not $userPath) {
    $userPath = ""
}
$pathParts = @()
foreach ($p in ($userPath -split ";")) {
    if ($p -and $p.Trim()) {
        $pathParts += $p.Trim()
    }
}
if ($pathParts -notcontains $BinDir) {
    if ($userPath.TrimEnd(";")) {
        $newPath = "$userPath;$BinDir"
    } else {
        $newPath = $BinDir
    }
    [Environment]::SetEnvironmentVariable("Path", $newPath, "User")
    $env:Path = "$BinDir;$env:Path"
    Write-Host "[*] Added to user PATH: $BinDir"
    Write-Host "    Open a new terminal if 'hatsoff' / 'hatsoff-agent' is not found yet."
} else {
    $env:Path = "$BinDir;$env:Path"
    Write-Host "[*] PATH already includes $BinDir"
}

Write-Host ""
Write-Host "[*] Desktop window uses Edge WebView2 (built into Windows 10/11)."
Write-Host "    If the window fails, run:  hatsoff --browser"
$wsl = Get-Command wsl -ErrorAction SilentlyContinue
if ($wsl) {
    Write-Host "[*] WSL detected - lab Run will prefer Kali WSL when installed."
} else {
    Write-Host "[*] No WSL found - chat works; lab Run uses Windows shell."
    Write-Host "    For Kali tools: install Kali in WSL, or run HatsOff on Kali."
}

Write-Host ""
Write-Host "========================================"
Write-Host "  Done. Start HatsOff with:"
Write-Host "    hatsoff-agent          # CLI (any terminal)"
Write-Host "    hatsoff                # desktop"
Write-Host "    hatsoff --browser"
Write-Host "  Update later with:"
Write-Host "    .\install.ps1 -Update"
Write-Host "========================================"
Write-Host ""

if ($NoRun) {
    exit 0
}

& $Wrapper
